[package]
name = "Utilscord"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5.0"
lofty = "0.21.1"
open_dmx = "1.1.1"
ratatui = { version = "0.28.1", features = ["crossterm"] }
rodio = "0.20.1"
rosc = "0.10.1"
tokio = { version = "1.41.0", features = ["rt"]} 
